# fly.toml app configuration file generated for canada-immigration-bot on 2023-07-14T19:00:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "canada-immigration-bot"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
