name: UpdateData

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

env:
  GITHUB_PAT: ${{secrets.PAT}}
  DATA_URL: ${{secrets.DATA_URL}}

permissions:
  contents: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run script
        run: deno run -A github_action.ts

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update data"
          git push
